### ISSUE TITLE
Embedded content is not refreshed

### ISSUE THREAD

**Issue by alarobric** [juhamust/mozaik-ext-embed#1]
If I embed an image, say from a highway webcam, it is not refreshed over time. Can an option be added to refresh at an interval?

example: 
`content: '<img src="http://images.drivebc.ca/bchighwaycam/pub/cameras/323.jpg">'`

**Comment by juhamust** [comment]
Perhaps `mozaik-ext-image` extension would suit you better, as it does support periodic refresh? https://github.com/juhamust/mozaik-ext-image 

This embed -extension uses iframe to embed _any_ content, thus relying source to update itself automatically (some webcam services do this, some don't). I'll add a note to project page to clarify this.

**Comment by juhamust** [comment]
Note added: https://github.com/juhamust/mozaik-ext-embed/commit/0d7b04aa5a96794c18570f288bf79bfdd13dfe0f

**Comment by alarobric** [comment]
Thanks for this. I missed the github notification from your message and worked out enough React and Javascript to implement this myself. I was just coming back here to start a pull request with a change to add a new embed.image type.
I took a look at the other extension but it doesn't seem to be rendering for me properly. I'll open an issue over there instead.
